<?php
// Additional hosting panel functions

function createEnhancedVirtualHost($domain, $documentRoot, $enableSSL = false, $username = '') {
    $vhostPath = rtrim(env('APACHE_VHOST_PATH', '/etc/apache2/sites-available'), '/');
    $vhostFile = $vhostPath . '/' . $domain . '.conf';
    
    $config = "# Virtual Host Configuration for $domain\n";
    $config .= "# Generated by Hosting Panel on " . date('Y-m-d H:i:s') . "\n\n";
    
    // HTTP Virtual Host
    $config .= "<VirtualHost *:80>\n";
    $config .= "    ServerName $domain\n";
    $config .= "    ServerAlias www.$domain\n";
    $config .= "    DocumentRoot \"$documentRoot/public_html\"\n";
    $config .= "    \n";
    $config .= "    # Logging\n";
    $config .= "    ErrorLog \"$documentRoot/logs/error.log\"\n";
    $config .= "    CustomLog \"$documentRoot/logs/access.log\" combined\n";
    $config .= "    \n";
    $config .= "    # Directory Configuration\n";
    $config .= "    <Directory \"$documentRoot/public_html\">\n";
    $config .= "        AllowOverride All\n";
    $config .= "        Require all granted\n";
    $config .= "        Options -Indexes +FollowSymLinks\n";
    $config .= "    </Directory>\n";
    $config .= "    \n";
    $config .= "    # PHP Configuration\n";
    $config .= "    <FilesMatch \\.php$>\n";
    $config .= "        SetHandler \"proxy:unix:/var/run/php/php8.3-fpm.sock|fcgi://localhost\"\n";
    $config .= "    </FilesMatch>\n";
    
    if ($enableSSL) {
        $config .= "    \n";
        $config .= "    # Redirect to HTTPS\n";
        $config .= "    RewriteEngine on\n";
        $config .= "    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]\n";
    }
    
    $config .= "</VirtualHost>\n";
    
    file_put_contents($vhostFile, $config);
    
    // Enable the site
    $reloadCmd = env('APACHE_RELOAD_CMD', 'systemctl reload apache2');
    if ($reloadCmd) {
        exec("a2ensite $domain.conf 2>&1", $output, $returnVar);
        exec($reloadCmd . ' 2>&1', $output, $returnVar);
    }
    
    return true;
}

function createDefaultWebPage($domain, $username, $enableSSL = false) {
    $protocol = $enableSSL ? 'https' : 'http';
    $sslBadge = $enableSSL ? "<span class='ssl-badge'>🔒 SSL Secured</span>" : "";
    $currentDate = date('Y-m-d H:i:s');
    
    return '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to ' . $domain . '</title>
    <style>
        body { font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; color: #333; }
        .container { background: white; border-radius: 15px; padding: 40px; text-align: center; box-shadow: 0 20px 40px rgba(0,0,0,0.1); max-width: 600px; margin: 20px; }
        h1 { color: #333; margin-bottom: 20px; font-size: 2.5em; }
        .status { background: #4CAF50; color: white; padding: 10px 20px; border-radius: 25px; display: inline-block; margin: 20px 0; font-weight: bold; }
        .info { background: #f5f5f5; padding: 20px; border-radius: 10px; margin: 20px 0; text-align: left; }
        .ssl-badge { background: #2196F3; color: white; padding: 5px 10px; border-radius: 15px; font-size: 0.8em; margin-left: 10px; }
        .footer { margin-top: 30px; color: #666; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎉 Welcome to ' . $domain . '</h1>
        ' . $sslBadge . '
        
        <div class="status">✅ Domain Active</div>
        
        <div class="info">
            <h3>📋 Domain Information</h3>
            <p><strong>Domain:</strong> ' . $domain . '</p>
            <p><strong>Owner:</strong> ' . $username . '</p>
            <p><strong>Protocol:</strong> ' . $protocol . '</p>
            <p><strong>Document Root:</strong> /public_html/</p>
            <p><strong>Created:</strong> ' . $currentDate . '</p>
        </div>
        
        <div class="info">
            <h3>🚀 Next Steps</h3>
            <ul style="text-align: left;">
                <li>Upload your website files to the public_html directory</li>
                <li>Configure DNS records to point to your server</li>
                <li>Set up email accounts through the control panel</li>
                <li>Configure backups for your data</li>
            </ul>
        </div>
        
        <div class="footer">
            <p>Powered by Professional Hosting Panel</p>
            <p>Generated on ' . $currentDate . '</p>
        </div>
    </div>
</body>
</html>';
}

function createSecureHtaccess() {
    return '# Security and Performance Configuration
# Generated by Hosting Panel

# Enable Rewrite Engine
RewriteEngine On

# Prevent access to sensitive files
<FilesMatch "^\.(htaccess|htpasswd|ini|phps|fla|psd|log|sh|sql|bak|backup)$">
    Order Allow,Deny
    Deny from all
</FilesMatch>

# Security headers
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options nosniff
    Header always set X-Frame-Options SAMEORIGIN
    Header always set X-XSS-Protection "1; mode=block"
</IfModule>

# Compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/plain text/html text/xml text/css application/xml application/xhtml+xml application/rss+xml application/javascript application/x-javascript
</IfModule>

# Browser Caching
<IfModule mod_expires.c>
    ExpiresActive on
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
</IfModule>';
}

function scheduleSSLCertificate($domainId, $domainName) {
    global $conn;
    
    $query = "INSERT INTO ssl_certificates (domain_id, status, auto_renew) VALUES (?, 'pending', 1)";
    $stmt = mysqli_prepare($conn, $query);
    if ($stmt) {
        mysqli_stmt_bind_param($stmt, "i", $domainId);
        mysqli_stmt_execute($stmt);
    }
    
    // Create SSL request file for background processing
    $sslQueue = '/tmp/ssl-queue.txt';
    file_put_contents($sslQueue, $domainName . "\n", FILE_APPEND | LOCK_EX);
    
    return true;
}
?>